### ISSUE TITLE
上传组件优化

### ISSUE THREAD

**Issue by jonny77** [hyperf-plus/ui#1]
1:后端返回了绝对的url ,应该直接展示图片 . 
2:返回code统一的问题,其他接口返回的 code都是0,到了上传组件就变成了200
3:上传出错的时候,重新上传一个图片,会提示  超出上传数量 
4:第三方云存储的domain应该只由一个地方进行维护.否则容易出错

**Comment by lphkxd** [comment]
3.0UI组件已发布基于amis
